<% if ENV['DATABASE_TYPE'] == 'mysql' %>
common: &common
  adapter: mysql2
  encoding: utf8mb4
  username: root
  password:
  host: 127.0.0.1
  port: 3306
<% elsif ENV['DATABASE_TYPE'] == 'sqlite' %>
common: &common
  adapter: sqlite3
  timeout: 30000
<% else %>
common: &common
  adapter: postgresql
  encoding: unicode
  pool: 10
  timeout: 5000
  min_messages: warning
  username: postgres
  password: postgres
  host: localhost
<% end %>

development:
  <<: *common
  database: motor_edge_dev

test:
  <<: *common
  database: motor_edge_test

production:
<% if ENV['DATABASE_URL'].to_s.empty? %>
  adapter: sqlite3
  timeout: 30000
  database: <%= ENV['WORKDIR'] %>motor-admin.sqlite3
<% else %>
  adapter: postgresql
  pool: 10
  url: <%= ENV['DATABASE_URL'] %>
<% end %>
